crawler:
  useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
  timeout: 10000
  webdriver:
    servers: http://192.168.219.103:4443/wd/hub


---

spring:
  profiles: deploy

crawler:
  webdriver:
    servers: http://192.168.219.103:4441/wd/hub
