spring.cloud:
    function:
      definition: lastCrawledItem
    stream:
      bindings:
        lastCrawledItem-out-0:
          destination : com.podo.helloprice.crawl.test.crawl-items
          binder : kafka
      kafka:
        binder:
          brokers: 192.168.219.101:9092
          auto-add-partitions: true
          min-partition-count: 1
          auto-create-topics: true

---

spring:
  profiles: deploy

  cloud:
    stream:
      bindings:
        lastCrawledItem-out-0.destination : com.podo.helloprice.crawl.crawl-items

