spring.profiles.include: core, jpa, stream

server:
  port: 28081

item.publish.expire.minute: 5

## Log
logging:
  file.name: helloprice-crawl-scheduler.%d{yyyy-MM-dd}-%i.log
  file.path: c://helloprice/logs/helloprice-crawl-scheduler

---

spring:
  profiles: deploy

server:
  port: 8080

## Log
logging:
  file.path: /data/logs
