server:
  port: 28081

item.publish.expire.minute: 5

spring:
  profiles:
    include: core, jpa, jpa-secret

  cloud:
    function:
      definition: lastCrawledItem
    stream:
      bindings:
        lastCrawledItem-out-0:
          destination : com.podo.helloprice.crawl.test.crawl-items
          binder : kafka
      kafka:
        binder:
          brokers: 192.168.219.103:9092
          auto-add-partitions: true
          min-partition-count: 1
          auto-create-topics: true

## Log
logging:
  file.name: helloprice-crawl-scheduler.%d{yyyy-MM-dd}-%i.log
  file.path: c://helloprice/logs/helloprice-crawl-scheduler

---

spring:
  profiles: deploy

  cloud:
    stream:
      bindings:
        lastCrawledItem-out-0.destination : com.podo.helloprice.crawl.crawl-items

server:
  port: 8080

## Log
logging:
  file.path: /data/logs
