spring.datasource:
  url: test
  username: test
  password: test
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  properties:
    hibernate:
      fomat_sql: true
      show_sql: true
      default_batch_fetch_size: 20
