spring.datasource:
  url: test
  username: test
  password: test
  driver-class-name: org.h2.Driver

spring.jpa:
  properties:
    hibernate:
      fomat_sql: true
      show_sql: true
      default_batch_fetch_size: 20
