spring.cloud:
  function:
    definition: consumeTelegramNotify;consumeEmailNotify;
  stream:
    bindings:
      consumeTelegramNotify-in-0:
        group: dev.com.podo.hellorpice
        destination: dev.com.podo.helloprice.notify.telegram
        binder: kafka
      consumeEmailNotify-in-0:
        group: dev.com.podo.hellorpice
        destination: dev.com.podo.helloprice.notify.email
        binder: kafka
    kafka:
      binder:
        brokers: localhost:9092
        auto-add-partitions: true
        min-partition-count: 1
        auto-create-topics: true
