spring.datasource:
  url: jdbc:mysql://192.168.219.103:3307/podo_helloprice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  username: cglee079
  password: lcg050179!
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  properties:
    hibernate:
      fomat_sql: false
      show_sql: false
      default_batch_fetch_size: 100
  open-in-view: false

decorator.datasource:
  p6spy:
    enable-logging: false
    multiline: false
    logging: slf4j