server:
  port: 17070

spring:
  profiles:
    include: core,  crawl-worker, jpa, jpa-secret

  cloud:
    function:
      definition: lastCrawledItem
    stream:
      bindings:
        lastCrawledItem-in-0:
          group : com.podo.helloprice.crawl.test.crawl-items.group-1
          destination : com.podo.helloprice.crawl.test.crawl-items
          binder : kafka
      kafka:
        binder:
          brokers: 192.168.219.103:9092
          auto-add-partitions: true
          min-partition-count: 1
          auto-create-topics: true


  batch:
    job:
      enabled: false

item:
  max_deadcount: 10


## Log
logging:
  file.name: helloprice-crawl-agent.%d{yyyy-MM-dd}-%i.log
  file.path: c://helloprice/logs/helloprice-crawl-agent

---

spring:
  profiles: deploy
  cloud:
    stream:
      bindings:
        lastCrawledItem-in-0:
          group : com.podo.helloprice.crawl.crawl-items.group-1
          destination : com.podo.helloprice.crawl.crawl-items

server:
  port: 8080

## Log
logging:
  file.path: /data/logs

