spring.datasource:
  url: jdbc:mysql://192.168.219.103:3307/podo_helloprice_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  username: cglee079
  password: lcg050179!
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  properties:
    hibernate:
      fomat_sql: true
      show_sql: true
      default_batch_fetch_size: 20
  open-in-view: false

decorator.datasource:
  p6spy:
    enable-logging: false
    multiline: false
    logging: slf4j
    #log-file: spy.log
    #log-format: # custom log format