spring.profiles.include: core,  crawl-worker, jpa, stream

server.port: 17070

spring.batch:
    job:
      enabled: false

item.max_deadcount: 10

## Log
logging:
  file.name: helloprice-crawl-agent.%d{yyyy-MM-dd}-%i.log
  file.path: c://helloprice/logs/helloprice-crawl-agent

---

server.port: 8080

## Log
logging:
  file.path: /data/logs

