spring.cloud:
  function:
    definition: lastCrawledItem
  stream:
    bindings:
      lastCrawledItem-in-0:
        group: com.podo.helloprice.crawl.crawl-items.group-1
        destination: com.podo.helloprice.crawl.crawl-items
        binder: kafka
    kafka:
      binder:
        brokers: 192.168.219.103:9092
        auto-add-partitions: true
        min-partition-count: 1
        auto-create-topics: true