server:
  port: 27070

spring:
  profiles:
    include: core, jpa, jpa-secret, telegram-secret

app:
  name: 헬로프라이스 v1.0
  telegram:
    help_url: https://www.podo-dev.com/blogs/185

user:
  max_error_count: 5
  max_item: 10

item:
  max_unknown_count: 1
  max_dead_count: 10

## Log
logging:
  file: helloprice-telegram.%d{yyyy-MM-dd}-%i.log
  path: c://helloprice/logs/helloprice-telegram

---

spring:
  profiles: deploy

server:
  port: 8080

## Log
logging:
  path: /data/logs