server.port: 27070

app:
  name: 헬로프라이스 - DEV
  version: v2.0
  help_url: https://www.podo-dev.com/blogs/185

crawler:
  useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
  read-timeout: 10000
  webdriver-remotes : http://192.168.219.103:4442/wd/hub

user:
  max_error_count: 5
  max_product: 10

product:
  max_unknown_count: 1
  max_dead_count: 10
  cache:
    expire_minutes: 1

email.key:
    expire_minutes: 5
