server:
  port: 27070

spring:
  profiles:
    include: core, crawl-worker, jpa, infra

app:
  name: 헬로프라이스
  version: v2.0
  telegram:
    help_url: https://www.podo-dev.com/blogs/185

user:
  max_error_count: 5
  max_item: 10

item:
  max_unknown_count: 1
  max_dead_count: 10
  cache:
    expire_minutes: 1


email:
  key:
    expire_minutes: 5 #Minutes


## Log
logging:
  file.name: helloprice-telegram.%d{yyyy-MM-dd}-%i.log
  file.path: c://helloprice/logs/helloprice-telegram



---

spring:
  profiles: deploy

server:
  port: 8080

## Log
logging:
  file.path: /data/logs
